### ISSUE TITLE
where is get_network_layer() code

### ISSUE THREAD

**Issue by fabioac** [jing-vision/lightnet#1]
Hi, 

i'm trying to build feature-viz, i included lightnet but when compiling get_network_layer is undefined. 
where is the definition/source code to include?

Thanks

**Comment by vinjn** [comment]
Have you synced the submodules?
It's part of the `darknet` submodule.

**Comment by fabioac** [comment]
thanks vinjn, i did not synced. i just had synced the features.

**Comment by vinjn** [comment]
@fabioac can we close this issue?

**Comment by fabioac** [comment]
Yes, thank you!
