### ISSUE TITLE
Is this project can be used on ubuntu?

### ISSUE THREAD

**Issue by q1vs5k5** [jing-vision/lightnet#12]

**Comment by vinjn** [comment]
I do have plan to port to Ubuntu, but no ETA at this moment.
You could use the darknet repo, which supports Ubuntu natively.

**Comment by isgursoy** [comment]
I will be working on ubuntu port. Then python may be. No ETA for me too.

**Comment by isgursoy** [comment]
What about current level of visualization support for layers in today's alexey/darknet?

**Comment by vinjn** [comment]
> What about current level of visualization support for layers in today's alexey/darknet?

Can you elaborate more?
