### ISSUE TITLE
submodule checkout error

### ISSUE THREAD

**Issue by thtfpcuser** [jing-vision/lightnet#13]
This is the error message:

> fatal: reference is not a tree: 6bb99873873f0fde08e8ecde754d5cb0e0ff97b8
Unable to checkout '6bb99873873f0fde08e8ecde754d5cb0e0ff97b8' in submodule path 'modules/yolo2_light'

The repository [yolo2_light](https://github.com/jing-vision/yolo2_light) is not up to date.

**Comment by vinjn** [comment]
yolo2_light is no longer necessary and removed, please update.
