### ISSUE TITLE
VIDEOIO(cvCreateFileCapture_FFMPEG_proxy(filename)): raised unknown C++ exception!

### ISSUE THREAD

**Issue by 1274085042** [jing-vision/lightnet#15]
@vinjn 
当我运行时，出现如下错误，请问怎样解决啊？
![feature_visualization](https://user-images.githubusercontent.com/32759044/73597012-dcb23700-4562-11ea-921b-385fb38333cd.png)

**Comment by vinjn** [comment]
Does the following cmd line work?
> feature-viz.exe -cfg=cfg\yolov3.cfg -weights=yolov3.weights data\dog.jpg

**Comment by 1274085042** [comment]
> 以下cmd行有效吗？
> 
> > feature-viz.exe -cfg = cfg \ yolov3.cfg -weights = yolov3.weights data \ dog.jpg

![feature-viz-error](https://user-images.githubusercontent.com/32759044/74103634-bf93ee80-4b88-11ea-8662-4ff0f4c73c04.png)

还是一样的，请问为什么出现这样的错误呢

**Comment by vinjn** [comment]
看着像是 opencv 的问题了，它把 jpg 当成视频来解码，但是解码出错了。
你换成摄像头、视频试试
> feature-viz.exe -cfg=cfg\yolov3.cfg -weights=yolov3.weights 0
> feature-viz.exe -cfg=cfg\yolov3.cfg -weights=yolov3.weights video.mp4

**Comment by 1274085042** [comment]
> 看着像是 opencv 的问题了，它把 jpg 当成视频来解码，但是解码出错了。
> 你换成摄像头、视频试试
> 
> > feature-viz.exe -cfg=cfg\yolov3.cfg -weights=yolov3.weights 0
> > feature-viz.exe -cfg=cfg\yolov3.cfg -weights=yolov3.weights video.mp4

谢谢您给的建议，但是我换成视频后还是不行
![feature_visualization1](https://user-images.githubusercontent.com/32759044/74211765-4f8e8100-4ccc-11ea-9c9d-f5780918fedc.png)

**Comment by vinjn** [comment]
重装opencv试试，使用 darknet.exe 会报错么

**Comment by 1274085042** [comment]
> 重装opencv试试，使用 darknet.exe 会报错么
使用`darknet.exe `正常



![feature_visualization2](https://user-images.githubusercontent.com/32759044/74433734-f117fd00-4e9b-11ea-8594-c31c4a100997.png)

**Comment by vinjn** [comment]
试试升级到 OpenCV 4.x？

**Comment by 1274085042** [comment]
> 试试升级到 OpenCV 4.x？

ok

**Comment by vinjn** [comment]
Does it work?

**Comment by 1274085042** [comment]
> Does it work?

YES,Thank you very much

**Comment by vinjn** [comment]
Good to hear that. closing.
