### ISSUE TITLE
feature-viz

### ISSUE THREAD

**Issue by 5sixty** [jing-vision/lightnet#16]
您好:
請問執行feature-viz這專案之前需要事先建立那些環境呢?我目前已經照步驟建立了vs2015的資料夾，但執行sln檔的時候遇到許多error。我的方式是把ligntnet載下來，並在feature-viz資料夾下執行，謝謝!

**Comment by vinjn** [comment]
hi，先确保 darknet 的项目能正确编译
https://github.com/jing-vision/lightnet#build-it
