### ISSUE TITLE
 How to configure the visualization

### ISSUE THREAD

**Issue by lvshuaigg** [jing-vision/lightnet#2]
How to configure the visualization file? Is similar to 
feature-viz.exe -cfg=cfg\alexnet.cfg -weights=alexnet.weights
Feature-viz.exe -cfg=cfg\darknet.cfg -weights=darknet.weights
Feature-viz.exe -cfg=cfg\darknet19.cfg -weights=darknet19.weights 
How to use it?

**Comment by vinjn** [comment]
Check https://github.com/jing-vision/lightnet/tree/master/feature-viz
