### ISSUE TITLE
Jing-pose error

### ISSUE THREAD

**Issue by Kingbadger3d** [jing-vision/lightnet#4]
Hey again, you must love me asking all these questions lol.

I generated the vs files for jing pose and compiled with no errors.
I get the jing-pose.exe in bin folder, ive downloaded the openpose.weight file listed on the github main page and used the openpose.cfg file located in jing-pose irectory.

But I get the following issue:

C:\lightnet\bin>jing-pose.exe openpose.cfg openpose.weight person.jpg
Failed to open: openpose.cfg
warning: Error opening file (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:808)
warning: openpose.weight (/build/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp:809)
Failed to open: openpose.weight
 Try to load cfg: openpose.cfg, weights: openpose.weight, clear = 0
batch: Using default '1'
learning_rate: Using default '0.001000'
momentum: Using default '0.900000'
decay: Using default '0.000100'
subdivisions: Using default '1'
policy: Using default 'constant'
max_batches: Using default '0'
layer     filters    size              input                output
   0 conv     64  3 x 3 / 1   200 x 200 x   3   ->   200 x 200 x  64 0.138 BF
   1 conv     64  3 x 3 / 1   200 x 200 x  64   ->   200 x 200 x  64 2.949 BF
   2 max          2 x 2 / 2   200 x 200 x  64   ->   100 x 100 x  64 0.003 BF
   3 conv    128  3 x 3 / 1   100 x 100 x  64   ->   100 x 100 x 128 1.475 BF
   4 conv    128  3 x 3 / 1   100 x 100 x 128   ->   100 x 100 x 128 2.949 BF
   5 max          2 x 2 / 2   100 x 100 x 128   ->    50 x  50 x 128 0.001 BF
   6 conv    256  3 x 3 / 1    50 x  50 x 128   ->    50 x  50 x 256 1.475 BF
   7 conv    256  3 x 3 / 1    50 x  50 x 256   ->    50 x  50 x 256 2.949 BF
   8 conv    256  3 x 3 / 1    50 x  50 x 256   ->    50 x  50 x 256 2.949 BF
   9 conv    256  3 x 3 / 1    50 x  50 x 256   ->    50 x  50 x 256 2.949 BF
  10 max          2 x 2 / 2    50 x  50 x 256   ->    25 x  25 x 256 0.001 BF
  11 conv    512  3 x 3 / 1    25 x  25 x 256   ->    25 x  25 x 512 1.475 BF
  12 conv    512  3 x 3 / 1    25 x  25 x 512   ->    25 x  25 x 512 2.949 BF
  13 conv    256  3 x 3 / 1    25 x  25 x 512   ->    25 x  25 x 256 1.475 BF
  14 conv    128  3 x 3 / 1    25 x  25 x 256   ->    25 x  25 x 128 0.369 BF
  15 conv    128  3 x 3 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.184 BF
  16 conv    128  3 x 3 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.184 BF
  17 conv    128  3 x 3 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.184 BF
  18 conv    512  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x 512 0.082 BF
  19 conv     38  1 x 1 / 1    25 x  25 x 512   ->    25 x  25 x  38 0.024 BF
  20 route  14
  21 conv    128  3 x 3 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.184 BF
  22 conv    128  3 x 3 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.184 BF
  23 conv    128  3 x 3 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.184 BF
  24 conv    512  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x 512 0.082 BF
  25 conv     19  1 x 1 / 1    25 x  25 x 512   ->    25 x  25 x  19 0.012 BF
  26 route  19 25 14
  27 conv    128  7 x 7 / 1    25 x  25 x 185   ->    25 x  25 x 128 1.450 BF
  28 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  29 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  30 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  31 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  32 conv    128  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.020 BF
  33 conv     38  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x  38 0.006 BF
  34 route  26
  35 conv    128  7 x 7 / 1    25 x  25 x 185   ->    25 x  25 x 128 1.450 BF
  36 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  37 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  38 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  39 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  40 conv    128  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.020 BF
  41 conv     19  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x  19 0.003 BF
  42 route  33 41 14
  43 conv    128  7 x 7 / 1    25 x  25 x 185   ->    25 x  25 x 128 1.450 BF
  44 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  45 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  46 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  47 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  48 conv    128  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.020 BF
  49 conv     38  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x  38 0.006 BF
  50 route  42
  51 conv    128  7 x 7 / 1    25 x  25 x 185   ->    25 x  25 x 128 1.450 BF
  52 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  53 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  54 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  55 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  56 conv    128  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.020 BF
  57 conv     19  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x  19 0.003 BF
  58 route  49 57 14
  59 conv    128  7 x 7 / 1    25 x  25 x 185   ->    25 x  25 x 128 1.450 BF
  60 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  61 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  62 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  63 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  64 conv    128  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.020 BF
  65 conv     38  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x  38 0.006 BF
  66 route  58
  67 conv    128  7 x 7 / 1    25 x  25 x 185   ->    25 x  25 x 128 1.450 BF
  68 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  69 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  70 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  71 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  72 conv    128  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.020 BF
  73 conv     19  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x  19 0.003 BF
  74 route  65 73 14
  75 conv    128  7 x 7 / 1    25 x  25 x 185   ->    25 x  25 x 128 1.450 BF
  76 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  77 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  78 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  79 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  80 conv    128  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.020 BF
  81 conv     38  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x  38 0.006 BF
  82 route  74
  83 conv    128  7 x 7 / 1    25 x  25 x 185   ->    25 x  25 x 128 1.450 BF
  84 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  85 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  86 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  87 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  88 conv    128  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.020 BF
  89 conv     19  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x  19 0.003 BF
  90 route  81 89 14
  91 conv    128  7 x 7 / 1    25 x  25 x 185   ->    25 x  25 x 128 1.450 BF
  92 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  93 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  94 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  95 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
  96 conv    128  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.020 BF
  97 conv     38  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x  38 0.006 BF
  98 route  90
  99 conv    128  7 x 7 / 1    25 x  25 x 185   ->    25 x  25 x 128 1.450 BF
 100 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
 101 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
 102 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
 103 conv    128  7 x 7 / 1    25 x  25 x 128   ->    25 x  25 x 128 1.004 BF
 104 conv    128  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x 128 0.020 BF
 105 conv     19  1 x 1 / 1    25 x  25 x 128   ->    25 x  25 x  19 0.003 BF
 106 route  105 97
Total BFLOPS 80.306
Loading weights from openpose.weight...
 seen 32
Done!
OpenCV Error: Assertion failed (!input.empty()) in create_netsize_im, file ..\src\post_process.cpp, line 495

**Comment by vinjn** [comment]
That's my fault, I didn't change the README.md.
Try `jing-pose.exe person.jpg`

**Comment by Kingbadger3d** [comment]
Ok that worked, but unfortunately I now have the same cuda error no kernel image is available but unlike in the darknet properties there is no cuda c/c++ settings to change the sm type from 52 to 50. Where did you set the sm type in this project?

Also If i try to compile the darknet version in modules directory the compile fails giving thousands of errors in regard to cstdint, Is this darknet version different o the one in darknetv3 folder? could you not use that darknet version instead of this one, at least that one compiles for me

Also could I contact you by skype for example so I can ask you some questions and chat about your project, being able to chat would make life easier than leaving comments on here. Cheers J
