### ISSUE TITLE
Jing-pose has been moved to a standalone repository

### ISSUE THREAD

**Issue by vinjn** [jing-vision/lightnet#5]
https://github.com/jing-interactive/DancingGaga

**Comment by vinjn** [comment]
#4

**Comment by Kingbadger3d** [comment]
Hey, Ive managed to get it working in the end but it's very slow, Is this normal behavior. Ive added a quick youtube video to show the problem and the skeletons get very bad cross connections. The openpose tensorflow.js implementation runs realtime at over 20 fps and that doesnt even use the gpu I think.

https://youtu.be/OXq3Yh1ZXrI

Cheers, J

**Comment by vinjn** [comment]
Are you running in Release build?

**Comment by Kingbadger3d** [comment]
Yep. as the video shows ive also got the GPU monitor running, it's using all the gpu. So you dont get such bad performance?

Hey look don't worry about it, Ill go back to Tensorflow.

**Comment by vinjn** [comment]
I am running at 30fps on gtx 1060.
