### ISSUE TITLE
i dont see any thing in yolov3-tiny; i load a picture(it have dog,bike,car)

### ISSUE THREAD

**Issue by yongcong1415** [jing-vision/lightnet#6]
![image](https://user-images.githubusercontent.com/16781337/46062151-7f062180-c19b-11e8-8594-383ff228bbbe.png)

**Comment by yongcong1415** [comment]
![image](https://user-images.githubusercontent.com/16781337/46062295-ee7c1100-c19b-11e8-9f0c-cebfe064f7ba.png)

the picture size is 1280*720;thanks,what error for me?

**Comment by yongcong1415** [comment]
the command:feature-viz.exe -cfg=yolov3-tiny.cfg -weights=yolov3-tiny.weights -names=coco.names
in this read picture:
![image](https://user-images.githubusercontent.com/16781337/46063389-47997400-c19f-11e8-88a8-02afae7e7b0f.png)

**Comment by vinjn** [comment]
feature-viz supports camera, video and image.
You can try pass `01.jpg` directly to feature-viz and see if it works, e.g.
> feature-viz.exe -cfg=yolov3-tiny.cfg -weights=yolov3-tiny.weights 01.jpg

**Comment by vinjn** [comment]
This is what I get from
> feature-viz.exe -cfg=yolov3-tiny.cfg -weights=yolov3-tiny.weights 01.jpg

![image](https://user-images.githubusercontent.com/558657/46345273-8a16f100-c676-11e8-8a5b-8f5bcaef96d1.png)

**Comment by vinjn** [comment]
@yongcong1415 can you verify and close?
