### ISSUE TITLE
where can i find __template-yolov3?

### ISSUE THREAD

**Issue by qindj** [jing-vision/lightnet#7]
Hello, 

sorry but where can i find __template-yolov3 mentioned by README ?

thx

**Comment by vinjn** [comment]
Oops, I didn't upload it :(

**Comment by vinjn** [comment]
@qindj plz check https://github.com/jing-vision/lightnet/tree/master/__template-yolov3

**Comment by qindj** [comment]
Many thanks! @vinjn
