### ISSUE TITLE
OPENCV ERROR to use darknet_viz

### ISSUE THREAD

**Issue by MingPap** [jing-vision/lightnet#8]
Hi~
when I try to use darknet_viz by following command
![2018-12-17 175656](https://user-images.githubusercontent.com/26671598/50079674-2d62b580-0225-11e9-890d-29ed33535d1b.jpg)

opencv ERROR out
![image](https://user-images.githubusercontent.com/26671598/50079718-4cf9de00-0225-11e9-96f6-4ef43e21b5a0.png)

could you figure it out?

**Comment by vinjn** [comment]
Do you have a camera device connected? I guess NO since
`Failed to open: 0`

If you don't have a camera device, you can use an image file to feed the network.
`feature-viz.exe /path/to/a/image.jpg -cfg=cfg\yolov3.cfg -weights=yolov3.weights -names=cfg\coco.names`
