### ISSUE TITLE
Feature visualization

### ISSUE THREAD

**Issue by naranjuelo** [jing-vision/lightnet#9]
Hi! Thank you for sharing your work. I want to use feature-viz with CPU, is that possible? 

I have compiled yolo lib for CPU but there is a function in lightnet.cpp that seems to need the GPU: cuda_pull_array(l->output_gpu, l->output, l->outputs*l->batch))

**Comment by vinjn** [comment]
I am not working on this feature, you need to add CPU support to that function yourself.

**Comment by vinjn** [comment]
@naranjuelo plz check my fix
